version: '3'
services:
  guacd:
    container_name: guacamole-guacd
    image: guacamole/guacd
    restart: always
    volumes:
      - /var/lib/egroupware/default/guacamole/drive:/drive:rw
      - /var/lib/egroupware/default/guacamole/record:/record:rw

  guacamole:
    container_name: guacamole
    depends_on:
      - guacd
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: localhost
      MYSQL_DATABASE: egroupware
      MYSQL_USER: egroupware
      MYSQL_PASSWORD: 'use db_passwd from header.inc.php'
      GUACAMOLE_HOME: /etc/guacamole
    image: guacamole/guacamole
    links:
      - guacd
    ports:
      - 127.0.0.1:8888:8080/tcp
    restart: always
    volumes:
      # use the host database EGroupware uses too:
      #    - RHEL/CentOS   /var/lib/mysql/mysql.sock:/var/run/mysqld/mysqld.sock
      #    - openSUSE/SLE  /var/run/mysql:/var/run/mysqld
      #    - Debian/Ubuntu /var/run/mysqld:/var/run/mysqld
      - /var/run/mysqld:/var/run/mysqld
      - /etc/egroupware-guacamole/guacamole-home:/etc/guacamole:ro
