version: '3'
services:
  guacd:
    container_name: guacamole-guacd
    image: guacamole/guacd
    restart: always
    volumes:
      - /var/lib/egroupware/default/guacamole/drive:/drive:rw
      - /var/lib/egroupware/default/guacamole/record:/record:rw

  guacamole:
    container_name: guacamole
    depends_on:
      - guacd
    environment:
      GUACD_HOSTNAME: guacd
      # MariaDB on host needs to bind on 172.17.0.1 (docker0) instead of localhost, as Guacamole/Tomcat has trouble to use socket
      MYSQL_HOSTNAME: 172.17.0.1
      MYSQL_DATABASE: egroupware
      MYSQL_USER: guacamole
      # guacamole-user-password must NOT contain special chars, eg. use the following to generate a save one: openssl rand --hex 16
      MYSQL_PASSWORD: guacamole-user-password
      GUACAMOLE_HOME: /etc/guacamole
      # see https://github.com/apache/guacamole-client/blob/master/guacamole-docker/bin/start.sh#L552
      OPENID_AUTHORIZATION_ENDPOINT: https://example.org/egroupware/openid/endpoint.php/authorize
      OPENID_JWKS_ENDPOINT: https://example.org/egroupware/openid/endpoint.php/jwks
      OPENID_ISSUER: https://example.org
      OPENID_CLIENT_ID: guacamole
      OPENID_REDIRECT_URI: https://example.org/guacamole/
    image: guacamole/guacamole
    links:
      - guacd
    ports:
      - 127.0.0.1:8888:8080/tcp
    restart: always
    volumes:
      - /etc/egroupware-guacamole/guacamole-home:/etc/guacamole:ro
    # set the ip-address of your docker host AND your official DNS name so Guacamole
    # can access EGroupware without the need to go over your firewall
    #extra_hosts:
    #- "example.org:172.17.0.1"
