version: '3'
services:
  guacd:
    container_name: guacamole-guacd
    image: guacamole/guacd
    restart: always
    volumes:
      - /var/lib/egroupware/default/guacamole/drive:/drive:rw
      - /var/lib/egroupware/default/guacamole/record:/record:rw

  guacamole:
    container_name: guacamole
    depends_on:
      - guacd
    environment:
      GUACD_HOSTNAME: guacd
      # MariaDB on host needs to bind on 172.17.0.1 (docker0) instead of localhost, as Guacamole/Tomcat has trouble to use socket
      MYSQL_HOSTNAME: 172.17.0.1
      MYSQL_DATABASE: egroupware
      MYSQL_USER: egroupware
      # package post-script sets password from /var/lib/egroupware/header.inc.php: GRANT ALL ON egroupware.* TO egroupware@`%` IDENTIFIED BY 'password'
      MYSQL_PASSWORD: 'use db_passwd from header.inc.php'
      GUACAMOLE_HOME: /etc/guacamole
    image: guacamole/guacamole
    links:
      - guacd
    ports:
      - 127.0.0.1:8888:8080/tcp
    restart: always
    volumes:
      - /etc/egroupware-guacamole/guacamole-home:/etc/guacamole:ro
    # set the ip-address of your docker host AND your official DNS name so Guacamole
    # can access EGroupware without the need to go over your firewall
    #extra_hosts:
    #- "example.org:172.17.0.1"
